"""phase 3 market data

Revision ID: 62848a719f99
Revises: f47c2c9d48ab
Create Date: 2026-08-11 18:35:45.515749

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "62848a719f99"
down_revision: str | None = "f47c2c9d48ab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_data_source_artifacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("environment", sa.String(length=32), nullable=False),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("dataset", sa.String(length=32), nullable=False),
        sa.Column("market", sa.String(length=16), nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("interval", sa.String(length=16), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_key", sa.Text(), nullable=False),
        sa.Column("raw_sha256", sa.String(length=64), nullable=False),
        sa.Column("raw_size", sa.BigInteger(), nullable=False),
        sa.Column("checksum_key", sa.Text(), nullable=True),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("expected_payload_sha256", sa.String(length=64), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(dataset = 'kline' AND interval IS NOT NULL) OR "
            "(dataset <> 'kline' AND interval IS NULL)",
            name=op.f("ck_market_data_source_artifacts_interval_only_for_klines"),
        ),
        sa.CheckConstraint(
            "(source_type = 'ARCHIVE' AND checksum_key IS NOT NULL AND "
            "checksum_sha256 IS NOT NULL AND expected_payload_sha256 = raw_sha256 "
            "AND period_start IS NOT NULL AND period_end IS NOT NULL "
            "AND period_end > period_start) OR "
            "(source_type = 'REST' AND checksum_key IS NULL AND "
            "checksum_sha256 IS NULL AND expected_payload_sha256 IS NULL "
            "AND period_start IS NULL AND period_end IS NULL)",
            name=op.f("ck_market_data_source_artifacts_source_specific_provenance"),
        ),
        sa.CheckConstraint(
            "dataset IN ('funding_rate', 'kline', 'mark_price', 'book_ticker')",
            name=op.f("ck_market_data_source_artifacts_valid_dataset"),
        ),
        sa.CheckConstraint(
            "environment IN ('testnet', 'production')",
            name=op.f("ck_market_data_source_artifacts_valid_environment"),
        ),
        sa.CheckConstraint(
            "market IN ('spot', 'usdm')", name=op.f("ck_market_data_source_artifacts_valid_market")
        ),
        sa.CheckConstraint(
            "source_type IN ('ARCHIVE', 'REST')",
            name=op.f("ck_market_data_source_artifacts_valid_source_type"),
        ),
        sa.CheckConstraint(
            "checksum_sha256 IS NULL OR length(checksum_sha256) = 64",
            name=op.f("ck_market_data_source_artifacts_valid_checksum_sha256"),
        ),
        sa.CheckConstraint(
            "expected_payload_sha256 IS NULL OR length(expected_payload_sha256) = 64",
            name=op.f("ck_market_data_source_artifacts_valid_expected_payload_sha256"),
        ),
        sa.CheckConstraint(
            "length(raw_key) > 0", name=op.f("ck_market_data_source_artifacts_nonempty_raw_key")
        ),
        sa.CheckConstraint(
            "length(raw_sha256) = 64", name=op.f("ck_market_data_source_artifacts_valid_raw_sha256")
        ),
        sa.CheckConstraint(
            "length(source_url) > 0",
            name=op.f("ck_market_data_source_artifacts_nonempty_source_url"),
        ),
        sa.CheckConstraint(
            "length(symbol) > 0", name=op.f("ck_market_data_source_artifacts_nonempty_symbol")
        ),
        sa.CheckConstraint(
            "raw_size > 0", name=op.f("ck_market_data_source_artifacts_positive_raw_size")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_data_source_artifacts")),
        sa.UniqueConstraint(
            "environment",
            "raw_key",
            name=op.f("uq_market_data_source_artifacts_environment_raw_key"),
        ),
        sa.UniqueConstraint(
            "id", "environment", name=op.f("uq_market_data_source_artifacts_id_environment")
        ),
    )
    op.create_index(
        "ix_market_data_source_artifacts_lookup",
        "market_data_source_artifacts",
        ["environment", "dataset", "market", "symbol", "fetched_at"],
        unique=False,
    )
    op.create_table(
        "book_ticker_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("environment", sa.String(length=32), nullable=False),
        sa.Column("market", sa.String(length=16), nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("bid_price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("bid_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("ask_price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("ask_quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("venue_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_update_id", sa.BigInteger(), nullable=True),
        sa.Column("source_artifact_id", sa.Uuid(), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "environment IN ('testnet', 'production')",
            name=op.f("ck_book_ticker_snapshots_valid_environment"),
        ),
        sa.CheckConstraint(
            "market IN ('spot', 'usdm')", name=op.f("ck_book_ticker_snapshots_valid_market")
        ),
        sa.CheckConstraint(
            "bid_price < ask_price", name=op.f("ck_book_ticker_snapshots_uncrossed_book")
        ),
        sa.CheckConstraint(
            "bid_price > 0 AND ask_price > 0", name=op.f("ck_book_ticker_snapshots_positive_prices")
        ),
        sa.CheckConstraint(
            "bid_quantity >= 0 AND ask_quantity >= 0",
            name=op.f("ck_book_ticker_snapshots_nonnegative_quantities"),
        ),
        sa.CheckConstraint(
            "length(symbol) > 0", name=op.f("ck_book_ticker_snapshots_nonempty_symbol")
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id", "environment"],
            ["market_data_source_artifacts.id", "market_data_source_artifacts.environment"],
            name=op.f("fk_book_ticker_snapshots_source_artifact_id_market_data_source_artifacts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_book_ticker_snapshots")),
        sa.UniqueConstraint(
            "source_artifact_id", name=op.f("uq_book_ticker_snapshots_source_artifact_id")
        ),
    )
    op.create_index(
        "ix_book_ticker_snapshots_series",
        "book_ticker_snapshots",
        ["environment", "market", "symbol", "collected_at"],
        unique=False,
    )
    op.create_table(
        "funding_rate_observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("environment", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("funding_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("funding_rate", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("mark_price", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("interval_hours", sa.Integer(), nullable=True),
        sa.Column("rate_type", sa.String(length=32), nullable=True),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("source_artifact_id", sa.Uuid(), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "environment IN ('testnet', 'production')",
            name=op.f("ck_funding_rate_observations_valid_environment"),
        ),
        sa.CheckConstraint(
            "source_type IN ('ARCHIVE', 'REST')",
            name=op.f("ck_funding_rate_observations_valid_source_type"),
        ),
        sa.CheckConstraint(
            "interval_hours IS NULL OR (interval_hours > 0 AND MOD(24, interval_hours) = 0)",
            name=op.f("ck_funding_rate_observations_valid_interval_hours"),
        ),
        sa.CheckConstraint(
            "length(symbol) > 0", name=op.f("ck_funding_rate_observations_nonempty_symbol")
        ),
        sa.CheckConstraint(
            "mark_price IS NULL OR mark_price > 0",
            name=op.f("ck_funding_rate_observations_positive_mark_price"),
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id", "environment"],
            ["market_data_source_artifacts.id", "market_data_source_artifacts.environment"],
            name=op.f(
                "fk_funding_rate_observations_source_artifact_id_market_data_source_artifacts"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_funding_rate_observations")),
        sa.UniqueConstraint(
            "environment",
            "symbol",
            "funding_time",
            "source_type",
            name=op.f("uq_funding_rate_observations_environment_symbol_funding_time_source_type"),
        ),
    )
    op.create_index(
        "ix_funding_rate_observations_series",
        "funding_rate_observations",
        ["environment", "symbol", "funding_time"],
        unique=False,
    )
    op.create_table(
        "kline_observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("environment", sa.String(length=32), nullable=False),
        sa.Column("market", sa.String(length=16), nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("interval", sa.String(length=16), nullable=False),
        sa.Column("open_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("close_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open_price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("high_price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("low_price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("close_price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("volume", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("quote_volume", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("trades", sa.BigInteger(), nullable=False),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("source_artifact_id", sa.Uuid(), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "environment IN ('testnet', 'production')",
            name=op.f("ck_kline_observations_valid_environment"),
        ),
        sa.CheckConstraint(
            "market IN ('spot', 'usdm')", name=op.f("ck_kline_observations_valid_market")
        ),
        sa.CheckConstraint(
            "source_type IN ('ARCHIVE', 'REST')",
            name=op.f("ck_kline_observations_valid_source_type"),
        ),
        sa.CheckConstraint(
            "close_time > open_time", name=op.f("ck_kline_observations_ordered_times")
        ),
        sa.CheckConstraint(
            "high_price >= open_price AND high_price >= close_price AND high_price >= low_price",
            name=op.f("ck_kline_observations_valid_high"),
        ),
        sa.CheckConstraint(
            "length(interval) > 0", name=op.f("ck_kline_observations_nonempty_interval")
        ),
        sa.CheckConstraint(
            "length(symbol) > 0", name=op.f("ck_kline_observations_nonempty_symbol")
        ),
        sa.CheckConstraint(
            "low_price <= open_price AND low_price <= close_price AND low_price <= high_price",
            name=op.f("ck_kline_observations_valid_low"),
        ),
        sa.CheckConstraint(
            "open_price > 0 AND high_price > 0 AND low_price > 0 AND close_price > 0",
            name=op.f("ck_kline_observations_positive_prices"),
        ),
        sa.CheckConstraint("trades >= 0", name=op.f("ck_kline_observations_nonnegative_trades")),
        sa.CheckConstraint(
            "volume >= 0 AND quote_volume >= 0",
            name=op.f("ck_kline_observations_nonnegative_volumes"),
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id", "environment"],
            ["market_data_source_artifacts.id", "market_data_source_artifacts.environment"],
            name=op.f("fk_kline_observations_source_artifact_id_market_data_source_artifacts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kline_observations")),
        sa.UniqueConstraint(
            "environment",
            "market",
            "symbol",
            "interval",
            "open_time",
            "source_type",
            name=op.f(
                "uq_kline_observations_environment_market_symbol_interval_open_time_source_type"
            ),
        ),
    )
    op.create_index(
        "ix_kline_observations_series",
        "kline_observations",
        ["environment", "market", "symbol", "interval", "open_time"],
        unique=False,
    )
    op.create_table(
        "mark_price_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("environment", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("venue_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mark_price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("index_price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("last_funding_rate", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("interest_rate", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("next_funding_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("estimated_settle_price", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("source_artifact_id", sa.Uuid(), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "environment IN ('testnet', 'production')",
            name=op.f("ck_mark_price_snapshots_valid_environment"),
        ),
        sa.CheckConstraint(
            "estimated_settle_price IS NULL OR estimated_settle_price > 0",
            name=op.f("ck_mark_price_snapshots_positive_estimated_settle_price"),
        ),
        sa.CheckConstraint(
            "length(symbol) > 0", name=op.f("ck_mark_price_snapshots_nonempty_symbol")
        ),
        sa.CheckConstraint(
            "mark_price > 0 AND index_price > 0",
            name=op.f("ck_mark_price_snapshots_positive_prices"),
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id", "environment"],
            ["market_data_source_artifacts.id", "market_data_source_artifacts.environment"],
            name=op.f("fk_mark_price_snapshots_source_artifact_id_market_data_source_artifacts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mark_price_snapshots")),
        sa.UniqueConstraint(
            "environment",
            "symbol",
            "venue_time",
            name=op.f("uq_mark_price_snapshots_environment_symbol_venue_time"),
        ),
    )
    op.create_index(
        "ix_mark_price_snapshots_series",
        "mark_price_snapshots",
        ["environment", "symbol", "venue_time"],
        unique=False,
    )
    op.create_table(
        "market_data_quality_assessments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("environment", sa.String(length=32), nullable=False),
        sa.Column("source_artifact_id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.String(length=16), nullable=False),
        sa.Column("dataset", sa.String(length=32), nullable=False),
        sa.Column("market", sa.String(length=16), nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("interval", sa.String(length=16), nullable=True),
        sa.Column("range_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("range_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("inserted_count", sa.Integer(), nullable=False),
        sa.Column("existing_count", sa.Integer(), nullable=False),
        sa.Column("duplicate_count", sa.Integer(), nullable=False),
        sa.Column("gap_count", sa.Integer(), nullable=False),
        sa.Column("conflict_count", sa.Integer(), nullable=False),
        sa.Column("details_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "dataset IN ('funding_rate', 'kline')",
            name=op.f("ck_market_data_quality_assessments_valid_dataset"),
        ),
        sa.CheckConstraint(
            "environment IN ('testnet', 'production')",
            name=op.f("ck_market_data_quality_assessments_valid_environment"),
        ),
        sa.CheckConstraint(
            "market IN ('spot', 'usdm')",
            name=op.f("ck_market_data_quality_assessments_valid_market"),
        ),
        sa.CheckConstraint(
            "source_type IN ('ARCHIVE', 'REST')",
            name=op.f("ck_market_data_quality_assessments_valid_source_type"),
        ),
        sa.CheckConstraint(
            "status IN ('PASS', 'BLOCKED')",
            name=op.f("ck_market_data_quality_assessments_valid_status"),
        ),
        sa.CheckConstraint(
            "row_count >= 0 AND inserted_count >= 0 AND existing_count >= 0 "
            "AND duplicate_count >= 0 AND gap_count >= 0 AND conflict_count >= 0",
            name=op.f("ck_market_data_quality_assessments_nonnegative_counts"),
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id", "environment"],
            ["market_data_source_artifacts.id", "market_data_source_artifacts.environment"],
            name=op.f(
                "fk_market_data_quality_assessments_source_artifact_id_market_data_source_artifacts"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_data_quality_assessments")),
    )
    op.create_index(
        "ix_market_data_quality_assessments_lookup",
        "market_data_quality_assessments",
        ["environment", "dataset", "market", "symbol", "evaluated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_market_data_quality_assessments_lookup", table_name="market_data_quality_assessments"
    )
    op.drop_table("market_data_quality_assessments")
    op.drop_index("ix_mark_price_snapshots_series", table_name="mark_price_snapshots")
    op.drop_table("mark_price_snapshots")
    op.drop_index("ix_kline_observations_series", table_name="kline_observations")
    op.drop_table("kline_observations")
    op.drop_index("ix_funding_rate_observations_series", table_name="funding_rate_observations")
    op.drop_table("funding_rate_observations")
    op.drop_index("ix_book_ticker_snapshots_series", table_name="book_ticker_snapshots")
    op.drop_table("book_ticker_snapshots")
    op.drop_index(
        "ix_market_data_source_artifacts_lookup", table_name="market_data_source_artifacts"
    )
    op.drop_table("market_data_source_artifacts")
    # ### end Alembic commands ###
