"""phase 0 audit spine

Revision ID: c02df1421a01
Revises: 
Create Date: 2026-08-09 17:06:06.809176

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c02df1421a01'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operational_job_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('command_json', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'RUNNING' AND finished_at IS NULL AND exit_code IS NULL) OR (status = 'SUCCEEDED' AND finished_at IS NOT NULL AND exit_code = 0) OR (status = 'FAILED' AND finished_at IS NOT NULL AND exit_code <> 0)", name=op.f('ck_operational_job_runs_consistent_terminal_state')),
    sa.CheckConstraint("status IN ('RUNNING', 'SUCCEEDED', 'FAILED')", name=op.f('ck_operational_job_runs_valid_status')),
    sa.CheckConstraint('length(job_name) > 0', name=op.f('ck_operational_job_runs_nonempty_job_name')),
    sa.CheckConstraint('length(source) > 0', name=op.f('ck_operational_job_runs_nonempty_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operational_job_runs'))
    )
    op.create_index('ix_operational_job_runs_name_started', 'operational_job_runs', ['job_name', 'started_at'], unique=False)
    op.create_index('ix_operational_job_runs_status_started', 'operational_job_runs', ['status', 'started_at'], unique=False)
    op.create_table('safety_control_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sequence_number', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('scope_type', sa.String(length=32), nullable=False),
    sa.Column('scope_key', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('automatic', sa.Boolean(), nullable=False),
    sa.Column('supersedes_event_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('ACTIVATE', 'CLEAR')", name=op.f('ck_safety_control_events_valid_action')),
    sa.CheckConstraint("environment IN ('testnet', 'production')", name=op.f('ck_safety_control_events_valid_environment')),
    sa.CheckConstraint("scope_type IN ('GLOBAL', 'VENUE', 'STRATEGY', 'CATEGORY', 'MARKET', 'DATA_PROVIDER', 'MODEL_VERSION', 'ACCOUNT')", name=op.f('ck_safety_control_events_valid_scope_type')),
    sa.CheckConstraint('length(actor) > 0', name=op.f('ck_safety_control_events_nonempty_actor')),
    sa.CheckConstraint('length(reason) > 0', name=op.f('ck_safety_control_events_nonempty_reason')),
    sa.CheckConstraint('length(scope_key) > 0', name=op.f('ck_safety_control_events_nonempty_scope_key')),
    sa.ForeignKeyConstraint(['supersedes_event_id'], ['safety_control_events.id'], name=op.f('fk_safety_control_events_supersedes_event_id_safety_control_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_safety_control_events')),
    sa.UniqueConstraint('sequence_number', name=op.f('uq_safety_control_events_sequence_number'))
    )
    op.create_index('ix_safety_control_events_scope_sequence', 'safety_control_events', ['environment', 'scope_type', 'scope_key', 'sequence_number'], unique=False)
    op.create_table('operational_health_assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trigger_job_run_id', sa.Uuid(), nullable=True),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('policy_version', sa.String(length=128), nullable=False),
    sa.Column('checks_json', sa.JSON(), nullable=False),
    sa.Column('automatic_control_event_ids_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("environment IN ('testnet', 'production')", name=op.f('ck_operational_health_assessments_valid_environment')),
    sa.CheckConstraint("status IN ('PASS', 'BLOCKED')", name=op.f('ck_operational_health_assessments_valid_status')),
    sa.ForeignKeyConstraint(['trigger_job_run_id'], ['operational_job_runs.id'], name=op.f('fk_operational_health_assessments_trigger_job_run_id_operational_job_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operational_health_assessments'))
    )
    op.create_index('ix_operational_health_assessments_status_time', 'operational_health_assessments', ['status', 'evaluated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_operational_health_assessments_status_time', table_name='operational_health_assessments')
    op.drop_table('operational_health_assessments')
    op.drop_index('ix_safety_control_events_scope_sequence', table_name='safety_control_events')
    op.drop_table('safety_control_events')
    op.drop_index('ix_operational_job_runs_status_started', table_name='operational_job_runs')
    op.drop_index('ix_operational_job_runs_name_started', table_name='operational_job_runs')
    op.drop_table('operational_job_runs')
    # ### end Alembic commands ###
