"""phase 5 carry proposals

Revision ID: d565bb42d888
Revises: 3f4619e0553e
Create Date: 2026-08-16 13:59:20.957583

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd565bb42d888'
down_revision: str | None = '3f4619e0553e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carry_proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('catalog_sha256', sa.String(length=64), nullable=False),
    sa.Column('mark_price', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('forecast_volatility', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('expected_funding_rate', sa.Numeric(precision=18, scale=12), nullable=False),
    sa.Column('settlements', sa.Integer(), nullable=False),
    sa.Column('gross_funding_bps', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_cost_bps', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('net_carry_bps_on_capital', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('breakeven_funding_bps', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('notional', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('perp_margin', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('margin_buffer', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('capital_required', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('stress_band', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('binding_constraint', sa.String(length=32), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('limits_json', sa.JSON(), nullable=False),
    sa.Column('outcomes_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("environment IN ('testnet', 'production')", name=op.f('ck_carry_proposals_valid_environment')),
    sa.CheckConstraint('(approved AND quantity > 0) OR (NOT approved AND quantity = 0)', name=op.f('ck_carry_proposals_approval_matches_size')),
    sa.CheckConstraint('quantity >= 0 AND notional >= 0', name=op.f('ck_carry_proposals_nonnegative_size')),
    sa.CheckConstraint('stress_band > 0', name=op.f('ck_carry_proposals_positive_stress_band')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carry_proposals'))
    )
    op.create_index('ix_carry_proposals_lookup', 'carry_proposals', ['environment', 'symbol', 'evaluated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_carry_proposals_lookup', table_name='carry_proposals')
    op.drop_table('carry_proposals')
    # ### end Alembic commands ###
